trigger:
  branches:
    include:
      - main

# Define o pool usando o agente self-hosted específico
pool:
  name: 'Azure Pipelines'  # Nome do pool onde o Hosted Agent está configurado
  demands:
    - agent.name -equals 'Hosted Agent'  # Nome exato do seu agente self-hosted

variables:
  # Versão do Python a ser usada
  PYTHON_VERSION: '3.9'

steps:
# Configura a versão do Python no ambiente do agente
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

# Instala as dependências do projeto usando o pip
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Instala dependências'

# Executa testes (caso tenha testes configurados)
- script: |
    pytest tests/
  displayName: 'Executa testes'

# Publica os artefatos gerados na build para a pipeline de Release
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
