-- Criação da tabela de clientes com colunas adicionais
CREATE TABLE clientes (
    cliente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    telefone VARCHAR2(15),
    endereco VARCHAR2(255),
    data_cadastro DATE DEFAULT SYSDATE
);

-- Criação da tabela de pedidos com colunas adicionais
CREATE TABLE pedidos (
    pedido_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cliente_id NUMBER NOT NULL,
    data_pedido DATE DEFAULT SYSDATE,
    valor_total NUMBER(10, 2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pendente',
    descricao VARCHAR2(255),
    data_entrega DATE,
    FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id)
);